version: '3'
services:
  kippu-mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=kippu
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
