spring:
    application:
        name: Kippu-api
    data:
        mongodb:
            uri: ${MONGO_URL}

server:
    port: 3000

kippu:
    api:
        client-id: ${KIPPU_CLIENT_ID}
        client-secret: ${KIPPU_CLIENT_SECRET}
